CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  ding_user_id VARCHAR(128) NOT NULL UNIQUE,
  union_id VARCHAR(128) NULL,
  name VARCHAR(128) NOT NULL,
  avatar_url VARCHAR(1024) NULL,
  mobile VARCHAR(32) NULL,
  email VARCHAR(255) NULL,
  org_email VARCHAR(255) NULL,
  title VARCHAR(128) NULL,
  job_number VARCHAR(128) NULL,
  work_place VARCHAR(255) NULL,
  department_name VARCHAR(255) NULL,
  ding_roles_json TEXT NULL,
  is_ding_admin BOOLEAN NOT NULL DEFAULT FALSE,
  is_boss BOOLEAN NOT NULL DEFAULT FALSE,
  is_senior BOOLEAN NOT NULL DEFAULT FALSE,
  is_leader BOOLEAN NOT NULL DEFAULT FALSE,
  manager_user_id VARCHAR(128) NULL,
  role ENUM('sales', 'purchase', 'logistics', 'admin') NOT NULL DEFAULT 'sales',
  commission_rate_percent DECIMAL(6,3) NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX idx_users_role (role),
  INDEX idx_users_union_id (union_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id CHAR(36) PRIMARY KEY,
  order_no VARCHAR(40) NOT NULL UNIQUE,
  customer_name VARCHAR(255) NOT NULL,
  customer_contact VARCHAR(255) NULL,
  shipping_address VARCHAR(1000) NULL,
  destination VARCHAR(255) NULL,
  deadline DATE NOT NULL,
  payment_method VARCHAR(32) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  freight DECIMAL(18,2) NOT NULL DEFAULT 0,
  goods_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  purchase_total DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_quantity INT UNSIGNED NOT NULL DEFAULT 0,
  received_cny DECIMAL(18,2) NULL,
  exchange_rate DECIMAL(12,6) NULL,
  commission_rate_percent DECIMAL(6,3) NULL,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at DATETIME(3) NULL,
  status ENUM('pending_purchase', 'purchasing', 'purchased', 'shipped', 'cancelled') NOT NULL DEFAULT 'pending_purchase',
  note TEXT NULL,
  owner_user_id CHAR(36) NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_orders_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
  INDEX idx_orders_status_deadline (status, deadline),
  INDEX idx_orders_owner_created (owner_user_id, created_at),
  INDEX idx_orders_customer (customer_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) PRIMARY KEY,
  order_id CHAR(36) NOT NULL,
  sku VARCHAR(128) NULL,
  name VARCHAR(255) NOT NULL,
  variant VARCHAR(255) NOT NULL,
  units_per_carton INT UNSIGNED NOT NULL,
  carton_count INT UNSIGNED NOT NULL,
  weight_kg DECIMAL(12,3) NOT NULL,
  volume_m3 DECIMAL(12,4) NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  unit_price DECIMAL(18,4) NOT NULL,
  total_price DECIMAL(18,2) NOT NULL,
  purchase_cost DECIMAL(18,2) NOT NULL,
  purchase_status ENUM('pending', 'completed') NOT NULL DEFAULT 'pending',
  purchased_by CHAR(36) NULL,
  purchased_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_products_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_products_purchaser FOREIGN KEY (purchased_by) REFERENCES users(id),
  UNIQUE KEY uk_order_sku_variant (order_id, sku, variant),
  INDEX idx_products_purchase (order_id, purchase_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attachments (
  id CHAR(36) PRIMARY KEY,
  order_id CHAR(36) NOT NULL,
  product_id CHAR(36) NULL,
  shipment_id CHAR(36) NULL,
  category ENUM('product', 'payment', 'logistics') NOT NULL,
  file_name VARCHAR(512) NOT NULL,
  file_size BIGINT UNSIGNED NULL,
  file_type VARCHAR(128) NULL,
  source_type VARCHAR(32) NULL,
  storage_provider VARCHAR(32) NULL,
  object_key VARCHAR(1024) NULL,
  uploaded_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_attachments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_attachments_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_attachments_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id),
  INDEX idx_attachments_object_key (storage_provider, object_key(128)),
  INDEX idx_attachments_product (product_id),
  INDEX idx_attachments_shipment (shipment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS shipments (
  id CHAR(36) PRIMARY KEY,
  order_id CHAR(36) NOT NULL,
  logistics_company VARCHAR(255) NOT NULL,
  tracking_no VARCHAR(255) NOT NULL,
  shipped_on DATE NOT NULL,
  estimated_arrival_on DATE NOT NULL,
  note TEXT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_shipments_creator FOREIGN KEY (created_by) REFERENCES users(id),
  UNIQUE KEY uk_shipment_order (order_id),
  UNIQUE KEY uk_tracking_company (logistics_company, tracking_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_status_history (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id CHAR(36) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NOT NULL,
  action VARCHAR(64) NOT NULL,
  actor_user_id CHAR(36) NOT NULL,
  detail JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_history_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_history_actor FOREIGN KEY (actor_user_id) REFERENCES users(id),
  INDEX idx_history_order_created (order_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS expenses (
  id CHAR(36) PRIMARY KEY,
  expense_no VARCHAR(40) NOT NULL UNIQUE,
  applicant_user_id CHAR(36) NOT NULL,
  category ENUM('travel', 'transport', 'meals', 'office', 'freight', 'client', 'other') NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  incurred_on DATE NOT NULL,
  description VARCHAR(1000) NOT NULL,
  is_reimbursed BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  reviewer_user_id CHAR(36) NULL,
  review_comment VARCHAR(1000) NULL,
  reviewed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_expenses_applicant FOREIGN KEY (applicant_user_id) REFERENCES users(id),
  CONSTRAINT fk_expenses_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(id),
  INDEX idx_expenses_applicant_created (applicant_user_id, created_at),
  INDEX idx_expenses_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS expense_attachments (
  id CHAR(36) PRIMARY KEY,
  expense_id CHAR(36) NOT NULL,
  file_name VARCHAR(512) NOT NULL,
  file_size BIGINT UNSIGNED NULL,
  file_type VARCHAR(128) NULL,
  storage_provider VARCHAR(32) NOT NULL DEFAULT 'oss',
  object_key VARCHAR(1024) NOT NULL,
  uploaded_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_expense_attachments_expense FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE,
  CONSTRAINT fk_expense_attachments_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id),
  INDEX idx_expense_attachments_expense (expense_id),
  INDEX idx_expense_attachments_object_key (object_key(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
